// Code generated by protoc-gen-go. DO NOT EDIT.
// source: places.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PlacesPb struct {
	Places               []*PlacePb `protobuf:"bytes,1,rep,name=Places,proto3" json:"Places,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PlacesPb) Reset()         { *m = PlacesPb{} }
func (m *PlacesPb) String() string { return proto.CompactTextString(m) }
func (*PlacesPb) ProtoMessage()    {}
func (*PlacesPb) Descriptor() ([]byte, []int) {
	return fileDescriptor_places_b8a0619dd5ec041e, []int{0}
}
func (m *PlacesPb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlacesPb.Unmarshal(m, b)
}
func (m *PlacesPb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlacesPb.Marshal(b, m, deterministic)
}
func (dst *PlacesPb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlacesPb.Merge(dst, src)
}
func (m *PlacesPb) XXX_Size() int {
	return xxx_messageInfo_PlacesPb.Size(m)
}
func (m *PlacesPb) XXX_DiscardUnknown() {
	xxx_messageInfo_PlacesPb.DiscardUnknown(m)
}

var xxx_messageInfo_PlacesPb proto.InternalMessageInfo

func (m *PlacesPb) GetPlaces() []*PlacePb {
	if m != nil {
		return m.Places
	}
	return nil
}

type PlacePb struct {
	ID                   string        `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PlaceID              string        `protobuf:"bytes,2,opt,name=PlaceID,proto3" json:"PlaceID,omitempty"`
	Name                 string        `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Address              *PlaceAddress `protobuf:"bytes,4,opt,name=Address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PlacePb) Reset()         { *m = PlacePb{} }
func (m *PlacePb) String() string { return proto.CompactTextString(m) }
func (*PlacePb) ProtoMessage()    {}
func (*PlacePb) Descriptor() ([]byte, []int) {
	return fileDescriptor_places_b8a0619dd5ec041e, []int{1}
}
func (m *PlacePb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlacePb.Unmarshal(m, b)
}
func (m *PlacePb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlacePb.Marshal(b, m, deterministic)
}
func (dst *PlacePb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlacePb.Merge(dst, src)
}
func (m *PlacePb) XXX_Size() int {
	return xxx_messageInfo_PlacePb.Size(m)
}
func (m *PlacePb) XXX_DiscardUnknown() {
	xxx_messageInfo_PlacePb.DiscardUnknown(m)
}

var xxx_messageInfo_PlacePb proto.InternalMessageInfo

func (m *PlacePb) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *PlacePb) GetPlaceID() string {
	if m != nil {
		return m.PlaceID
	}
	return ""
}

func (m *PlacePb) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlacePb) GetAddress() *PlaceAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

type PlaceAddress struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=Lat,proto3" json:"Lat,omitempty"`
	Lng                  float64  `protobuf:"fixed64,2,opt,name=Lng,proto3" json:"Lng,omitempty"`
	LocationType         string   `protobuf:"bytes,3,opt,name=LocationType,proto3" json:"LocationType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceAddress) Reset()         { *m = PlaceAddress{} }
func (m *PlaceAddress) String() string { return proto.CompactTextString(m) }
func (*PlaceAddress) ProtoMessage()    {}
func (*PlaceAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_places_b8a0619dd5ec041e, []int{2}
}
func (m *PlaceAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceAddress.Unmarshal(m, b)
}
func (m *PlaceAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceAddress.Marshal(b, m, deterministic)
}
func (dst *PlaceAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceAddress.Merge(dst, src)
}
func (m *PlaceAddress) XXX_Size() int {
	return xxx_messageInfo_PlaceAddress.Size(m)
}
func (m *PlaceAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceAddress.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceAddress proto.InternalMessageInfo

func (m *PlaceAddress) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *PlaceAddress) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *PlaceAddress) GetLocationType() string {
	if m != nil {
		return m.LocationType
	}
	return ""
}

func init() {
	proto.RegisterType((*PlacesPb)(nil), "pb.PlacesPb")
	proto.RegisterType((*PlacePb)(nil), "pb.PlacePb")
	proto.RegisterType((*PlaceAddress)(nil), "pb.PlaceAddress")
}

func init() { proto.RegisterFile("places.proto", fileDescriptor_places_b8a0619dd5ec041e) }

var fileDescriptor_places_b8a0619dd5ec041e = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xd0, 0x31, 0x6b, 0x85, 0x30,
	0x14, 0x05, 0x60, 0x12, 0x45, 0xdb, 0xab, 0x14, 0xb9, 0x53, 0x46, 0x49, 0x17, 0xe9, 0x60, 0xc1,
	0xfe, 0x82, 0x82, 0x8b, 0x20, 0x45, 0x42, 0xe9, 0x9e, 0xa8, 0x48, 0xa1, 0x35, 0xc1, 0xb8, 0xf4,
	0xdf, 0x17, 0xef, 0x8b, 0x8f, 0xf7, 0xb6, 0x93, 0xef, 0x04, 0x0e, 0x5c, 0xc8, 0xdd, 0x8f, 0x1e,
	0x67, 0x5f, 0xbb, 0xcd, 0xee, 0x16, 0xb9, 0x33, 0xf2, 0x15, 0x1e, 0x06, 0xb2, 0xc1, 0xe0, 0x33,
	0x24, 0x97, 0x2c, 0x58, 0x19, 0x55, 0x59, 0x93, 0xd5, 0xce, 0xd4, 0x24, 0x83, 0x51, 0xa1, 0x92,
	0x1e, 0xd2, 0x40, 0xf8, 0x04, 0xbc, 0x6b, 0x05, 0x2b, 0x59, 0xf5, 0xa8, 0x78, 0xd7, 0xa2, 0x08,
	0x55, 0xd7, 0x0a, 0x4e, 0x78, 0x3e, 0x11, 0x21, 0xfe, 0xd0, 0xbf, 0xb3, 0x88, 0x88, 0x29, 0xe3,
	0x0b, 0xa4, 0xef, 0xd3, 0xb4, 0xcd, 0xde, 0x8b, 0xb8, 0x64, 0x55, 0xd6, 0x14, 0xd7, 0xb9, 0xe0,
	0xea, 0xfc, 0x20, 0xbf, 0x20, 0xbf, 0x2d, 0xb0, 0x80, 0xa8, 0xd7, 0x3b, 0x4d, 0x33, 0x75, 0x44,
	0x92, 0x75, 0xa1, 0xdd, 0x43, 0xd6, 0x05, 0x25, 0xe4, 0xbd, 0x1d, 0xf5, 0xfe, 0x6d, 0xd7, 0xcf,
	0x3f, 0x77, 0x6e, 0xdf, 0x99, 0x49, 0xe8, 0x10, 0x6f, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7d,
	0xdb, 0x1f, 0xdb, 0x18, 0x01, 0x00, 0x00,
}
