// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wifi.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Wifi struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PlaceID              string   `protobuf:"bytes,2,opt,name=PlaceID,proto3" json:"PlaceID,omitempty"`
	DownSpeed            uint64   `protobuf:"varint,3,opt,name=DownSpeed,proto3" json:"DownSpeed,omitempty"`
	UpSpeed              uint64   `protobuf:"varint,4,opt,name=UpSpeed,proto3" json:"UpSpeed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wifi) Reset()         { *m = Wifi{} }
func (m *Wifi) String() string { return proto.CompactTextString(m) }
func (*Wifi) ProtoMessage()    {}
func (*Wifi) Descriptor() ([]byte, []int) {
	return fileDescriptor_wifi_59396c2e71083a6a, []int{0}
}
func (m *Wifi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wifi.Unmarshal(m, b)
}
func (m *Wifi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wifi.Marshal(b, m, deterministic)
}
func (dst *Wifi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wifi.Merge(dst, src)
}
func (m *Wifi) XXX_Size() int {
	return xxx_messageInfo_Wifi.Size(m)
}
func (m *Wifi) XXX_DiscardUnknown() {
	xxx_messageInfo_Wifi.DiscardUnknown(m)
}

var xxx_messageInfo_Wifi proto.InternalMessageInfo

func (m *Wifi) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Wifi) GetPlaceID() string {
	if m != nil {
		return m.PlaceID
	}
	return ""
}

func (m *Wifi) GetDownSpeed() uint64 {
	if m != nil {
		return m.DownSpeed
	}
	return 0
}

func (m *Wifi) GetUpSpeed() uint64 {
	if m != nil {
		return m.UpSpeed
	}
	return 0
}

func init() {
	proto.RegisterType((*Wifi)(nil), "pb.Wifi")
}

func init() { proto.RegisterFile("wifi.proto", fileDescriptor_wifi_59396c2e71083a6a) }

var fileDescriptor_wifi_59396c2e71083a6a = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xcf, 0x4c, 0xcb,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xca, 0xe0, 0x62, 0x09, 0xcf,
	0x4c, 0xcb, 0x14, 0xe2, 0xe3, 0x62, 0xf2, 0x74, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62,
	0xf2, 0x74, 0x11, 0x92, 0xe0, 0x62, 0x0f, 0xc8, 0x49, 0x4c, 0x4e, 0xf5, 0x74, 0x91, 0x60, 0x02,
	0x0b, 0xc2, 0xb8, 0x42, 0x32, 0x5c, 0x9c, 0x2e, 0xf9, 0xe5, 0x79, 0xc1, 0x05, 0xa9, 0xa9, 0x29,
	0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0x08, 0x01, 0x90, 0xbe, 0xd0, 0x02, 0x88, 0x1c, 0x0b,
	0x58, 0x0e, 0xc6, 0x4d, 0x62, 0x03, 0x5b, 0x6a, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x60,
	0x5b, 0x7b, 0x82, 0x00, 0x00, 0x00,
}
